### PR TITLE
Water quality and modifications.

### LINKED ISSUE #11: Add simple water quality routine.
Barry Evans has provided an algorithm to extend TR-55 results with simple water quality predictions based on the same workflow of the existing model.

### PR DESCRIPTION
**Pull request by jamesmcclain**
Add the ability to do water quality computations, including in the
presence of modifications.  Tests have been implemented for all of the
basic components which underlie the complete calculation, be we still
lack sufficient data to evaluate how accurately this code implements the
model.

This pull request includes work by @mmcfarland, as well as myself.

Fixes WikiWatershed/tr-55#11

### CODE REVIEW

**Comment by mmcfarland** [comment]
This looks good for calculating the runoff and quality metrics for the entire query area, since we're calculating modifications additionally to the entire area, can we preserve these values?  That way we could report the change (reduction, presumably) that each BMP or reclassification was responsible for in the web app.

**Comment by jamesmcclain** [comment]
Okay, I have modified the code to preserve the individual sub-parts of the calculation.

**Comment by jamesmcclain** [comment]
This is what the output looks like right now:
```Python
{u'modified': {u'bod': 1155.5832690023512,
               u'cell_count': 147,
               u'distribution': {u'a:deciduous_forest': {u'bod': 1.9676947491691286,
                                                         u'cell_count': 72,
                                                         u'et': 24.675262500000017,
                                                         u'inf': 34.53218880673186,
                                                         u'runoff': 0.7999320266014792,
                                                         u'tn': 0.006128885284297285,
                                                         u'tp': 0.00019354374581991428,
                                                         u'tss': 1.258034347829443},
                                 u'c:commercial': {u'bod': 619.3321622220828,
                                                   u'cell_count': 42,
                                                   u'et': 17.42526,
                                                   u'inf': 16.198443763932524,
                                                   u'runoff': 21.23295052178176,
                                                   u'tn': 4.545098932436254,
                                                   u'tp': 0.7192244464514511,
                                                   u'tss': 126.3137934080361},
                                 u'd:hi_residential': {u'bod': 534.2834120310993,
                                                       u'cell_count': 33,
                                                       u'et': 15.08352545454543,
                                                       u'inf': 13.967458770273502,
                                                       u'runoff': 24.498158107332266,
                                                       u'tn': 3.101560485095788,
                                                       u'tp': 0.5206999354540374,
                                                       u'tss': 63.842339912190674}},
               u'et': 20.450586122448982,
               u'inf': 24.67740388835977,
               u'runoff': 11.957947247429287,
               u'tn': 7.652788302816338,
               u'tp': 1.2401179256513084,
               u'tss': 191.41416766805622},
 u'unmodified': {u'bod': 1762.555509187117,
                 u'cell_count': 147,
                 u'distribution': {u'a:deciduous_forest': {u'bod': 0.0,
                                                           u'cell_count': 72,
                                                           u'et': 26.51670000000007,
                                                           u'inf': 34.91810000000001,
                                                           u'runoff': 0.0,
                                                           u'tn': 0.0,
                                                           u'tp': 0.0,
                                                           u'tss': 0.0},
                                   u'c:commercial': {u'bod': 1061.0138827829708,
                                                     u'cell_count': 42,
                                                     u'et': 2.272860000000005,
                                                     u'inf': 4.430079770137537,
                                                     u'runoff': 36.375400229862464,
                                                     u'tn': 7.786472849455671,
                                                     u'tp': 1.2321451541995787,
                                                     u'tss': 216.39549270630107},
                                   u'd:hi_residential': {u'bod': 701.5416264041463,
                                                         u'cell_count': 33,
                                                         u'et': 6.818579999999993,
                                                         u'inf': 8.361629213022574,
                                                         u'runoff': 32.167342828759615,
                                                         u'tn': 4.072508593956273,
                                                         u'tp': 0.6837058223430238,
                                                         u'tss': 83.8282790872751}},
                 u'et': 15.167861632653095,
                 u'inf': 20.24558036990151,
                 u'runoff': 17.614211721110824,
                 u'tn': 11.858981443411944,
                 u'tp': 1.9158509765426026,
                 u'tss': 300.2237717935762}}
```
this shows how the modifications effect the various subregions within the area.  It does not explicitly show the contributions made to each subregion by the modified and unmodified parts, but it shows how each subregion is changed.  Is this what you had in mind?

**Comment by mmcfarland** [comment]
+1  As discussed, we'll enhance this output with the change in values produced by each modification in future work.

**Comment by jamesmcclain** [comment]
Okay, sounds like a winner.

**Pull request merged**
