### PR TITLE
Prepare release 1.0.0 - Update changelog.

### PR DESCRIPTION
**Pull request by lliss**

### CODE REVIEW

**Comment by mmcfarland** [comment]
I think you should also update the version number in the commit and re-title it to the new version number (1.0.0?).

https://github.com/WikiWatershed/tr-55/blob/develop/setup.py#L16

**Comment by lliss** [comment]
That one better?

**Comment by mmcfarland** [comment]
Actually, you can do this within a `git flow` release workflow, I wrote up some instructions here https://github.com/WikiWatershed/tr-55#deployments

I'm a fan of the plain `1.0.0` commit title since it stands out as a release commit.

**Comment by mmcfarland** [comment]
Those instructions also include the auto pypi deployment, if you do a `git push --tags` subsequently.

**Pull request merged**
