### PR TITLE
Simplify logic and remove unneeded code

### PR DESCRIPTION
**Pull request by jamesmcclain**
This is just an enhancement, not really required for anything.  This patch does two things:
   * It remove the code and tests for simulating an entire year.  Initially, it was unclear whether this functionality was needed, now it appears that it is not.  If it is ever needed in the future, the same result can be achieved by calling the `simulate_day` function 365 times and add the results together, which is essentially all this code was doing.
   * A collection of special cases in the `create_modified_census` function has been replaced with simple arithmetic.  These changes make the function easier to understand and maintain (in my opinion).

### CODE REVIEW

**Comment by mmcfarland** [comment]
Tests still pass and a nice reduction in code, looks good.

**Comment by jamesmcclain** [comment]
+1?

**Comment by mmcfarland** [comment]
+1

**Comment by jamesmcclain** [comment]
Many thanks for reviewing.

**Pull request merged**
