### PR TITLE
Updates to TR55 & Pitts as recommended by Stroud

### PR DESCRIPTION
**Pull request by mmcfarland**
After evaluating the model execution in the MMW application, Stroud
provided adjustments to the model and it's inputs.  Tests were updated
accordingly and some removed.  The removed tests were testing that the
threshold of values was relatively inline with some previous expected
output of the model, but due to these changes, that threshold proved to
be larger than reasonable to assert in the tests.

Connects #57 (which lists the changes desired by Stroud)

Tagging @SRGDamia1 to take a look at the implementation changes as well.

### CODE REVIEW

**Comment by lliss** [comment]
+1. Confirmed the new values are in place. All test pass.

**Comment by jamesmcclain** [comment]
I will begin testing by noon.

**Comment by mmcfarland** [comment]
I'm going to take my +1 and merge so I can update the release.

**Comment by jamesmcclain** [comment]
Okay, sounds good.

**Pull request merged**
