### PR TITLE
Feature/lol/align nlcd strings2

### PR DESCRIPTION
**Pull request by lliss**
Related to https://github.com/WikiWatershed/model-my-watershed/issues/765

Rework all the strings and tests so that the keys used to run a tr55 model match those used by NLCD.

Note that I intend to squash this all to a single commit (or two) but I used single commits to test after each rename and it will probably make it easier to review in smaller chunks.

### CODE REVIEW

**Comment by lliss** [comment]
Looping in @mmcfarland as well.

**Comment by jamesmcclain** [comment]
+1

A couple of comments:
   * These changes kind of un-do https://github.com/WikiWatershed/model-my-watershed/pull/671
   * These changes also need to be made in `geoprocessing.py` (https://github.com/WikiWatershed/model-my-watershed/blob/c3002294b4afea572c5ed36ef6f0450b2f0e4707/src/mmw/apps/modeling/geoprocessing.py#L17-L32) or the geoprocessing code will stop working.

**Comment by lliss** [comment]
> These changes kind of un-do WikiWatershed/model-my-watershed#671

That appears to be the purpose of https://github.com/WikiWatershed/model-my-watershed/issues/765

**Comment by lliss** [comment]
> These changes also need to be made in geoprocessing.py (https://github.com/WikiWatershed/model-my-watershed/blob/c3002294b4afea572c5ed36ef6f0450b2f0e4707/src/mmw/apps/modeling/geoprocessing.py#L17-L32) or the geoprocessing code will stop working.

Yes.  New PR for that will be arriving shortly.

**Comment by jamesmcclain** [comment]
Okay, it sounds like all is well.

**Comment by lliss** [comment]
> Why is this a placeholder and not actually added?

@jamesmcclain's comment in the code led me to believe that data was not available. I looked at the TR55 document and it provides no values for snow or ice.

**Comment by lliss** [comment]
> pasture shows up twice in this list

Fixed in 62fa0c5

**Comment by jamesmcclain** [comment]
If I recall, I think that I was drawing the values from two different sources (the other one was a table in one of the PDFs from Stroud[?]).  I must have meant that it was not in the other source.

**Comment by lliss** [comment]
> Same, I think prairie -> grassland is more correct per #765

I replaced it based on the NLCD number being used. prairie was using 21. I can change that though.

**Comment by lliss** [comment]
> I think separated was more grammatically correct?

Fixed that.

**Comment by lliss** [comment]
When we do merge this we should cut a new release. In semver world, we'd bump the major version number since this breaks the API. Should we make a 1.0.0 release?

**Comment by mmcfarland** [comment]
> When we do merge this we should cut a new release. In semver world, we'd bump the major version number since this breaks the API. Should we make a 1.0.0 release?

Yep, let's keep semver for this, and also keep in mind we've been maintaining a changelog for releases:
https://github.com/WikiWatershed/tr-55/blob/develop/CHANGELOG.md

**Comment by jamesmcclain** [comment]
I don't know what the roadmap is, but I would be in favor of removing some of the unused code and doing a general cleanup before the next release.

**Comment by lliss** [comment]
> I don't know what the roadmap is, but I would be in favor of removing some of the unused code and doing a general cleanup before the next release.

That's a good plan, however I'd vote to get this change out (since it will be blocking other PRs in MMW) and then do cleanup and refactor which shouldn't change the API. I'm thinking we can release a 1.0.1 shortly after 1.0.0.

**Comment by jamesmcclain** [comment]
That makes sense.

**Pull request merged**
