### PR TITLE
Improved Water Quality EMC's

### PR DESCRIPTION
**Pull request by SRGDamia1**
New event mean concentration numbers per updated sources from Barry Evans.

### CODE REVIEW

**Comment by SRGDamia1** [comment]
This doesn't change anything at all in the implementation of the model; it's just an improvement to the numbers in the tables and an update of the tests to match.

**Comment by SRGDamia1** [comment]
Also, @aufdenkampe can confirm, but if it does end up being more than the fast fix I hope it is, this is not a very high priority given the current poor visualization of this data (https://github.com/WikiWatershed/model-my-watershed/issues/1046).

**Comment by mmcfarland** [comment]
Thanks @SRGDamia1, changes look good and all the tests pass.  I'll merge this in and create a task to make a new release of the model and update the dependency it in the next release of MMW.

Since the model results will now be changing, we'll also want to clear out the results of saved projects so that users whose results are based on the previous figures will have them recalculated next time the load the project.

**Comment by aufdenkampe** [comment]
Awesome!

Sara, it might be good to write up a paragraph, while it's still fresh, about expecting changes to output, to include in our next news post for the next release.

Sent from my iPhone

On May 25, 2017, at 10:39 AM, Matthew McFarland <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @SRGDamia1<https://github.com/srgdamia1>, changes look good and all the tests pass. I'll merge this in and create a task to make a new release of the model and update the dependency it in the next release of MMW.

Since the model results will now be changing, we'll also want to clear out the results of saved projects so that users whose results are based on the previous figures will have them recalculated next time the load the project.

-

**Pull request merged**
